### ISSUE TITLE
How to output config values, getting an error?

### ISSUE THREAD

**Issue by sananes** [fvsch/kirby-twig#20]
Hi guys,

When using `{{ l__get(configName, defaultValue) }}` to get any config values that I have in site/languages/ gives me an error of `Unknown "l__get" function.` Any reason why?

Your help will be much appreciated! Thanks in advance :)

**Comment by fvsch** [comment]
Hi, I can’t reproduce this with Kirby 3.0.0.

With default config, and no language config files:

```
Outputs "bar": {{ l__get('foo', 'bar') }}
```

Did you use the `c::set('twig.functions', […]);` and/or `c::set('twig.function.*`, …);` config? If yes, can you show your config?

Can you try defining a `l::get` shortcut in your config?

```php
c::set('twig.function.l', 'l::get');
```

```twig
{{ l('foo', 'bar') }}
```

**Comment by sananes** [comment]
First of all, thanks for the super speedy response! That worked an absolute treat, thanks a bunch @fvsch !
