### ISSUE TITLE
How to load twig templates with Kirby function tpl::load

### ISSUE THREAD

**Issue by designbydc** [fvsch/kirby-twig#23]
Hi,

is it possible to load or pass twig templates with the tpl::load() function?

```
array(
	'pattern' => array('(:any)/(:any)/details/(:any)'),
	'action'  => function($i18n, $section, $details) {
		$items_section = site()->visit($section, $i18n)->children()->visible();
		$items_topic = $items_section->children()->findBy('slug', $details);

		if ( isset($items_topic) && !empty($items_topic) ){
			tpl::$data = array_merge(tpl::$data, array(
				'kirby' => kirby(),
				'site' => site(),
				'pages' => pages(),
				'page' => $items_topic
			), $items_topic->templateData());

			echo tpl::load( kirby()->roots()->templates() . DS . 'sometemplate.twig');
		}
	},
	'method' => 'GET'
)
```

Of course this doesn't works because the file will not be rendered! Maybe someone can help me please or can show me another solution?

**Comment by fvsch** [comment]
Kirby’s `tpl::load` will only load PHP scripts.
But you should be able to use the `twig()` helper function instead. See the README:
https://github.com/fvsch/kirby-twig#rendering-a-template-in-php-the-twig-helper

**Comment by designbydc** [comment]
I've tried just the twig() helper function but I get the error "Call to undefined function twig()". I also register the Twig Plugin first with Kirby\Twig\Plugin::register(); but than I get a 500 error.

**Comment by fvsch** [comment]
See my answer on the kirby forum: https://forum.getkirby.com/t/how-to-set-twig-files-in-template-loader/7866/7?u=fvsch
