### ISSUE TITLE
Can't register namespaces, functions & filters in plugins

### ISSUE THREAD

**Issue by kraftner** [fvsch/kirby-twig#25]
It seems as if using [`$kirby->options`](https://github.com/fvsch/kirby-twig/blob/1bc2fcad6af4702aebac04fd9a523fb463f030e9/src/TwigEnv.php#L148) has the downside that anything you set outside/after `config.php` is being ignored. That is kind of sad because unless I got something really wrong you can't add anything from plugins now in contrast to [what the docs say](https://github.com/fvsch/kirby-twig/blob/master/doc/plugins.md#using-twig-in-plugin-code).

I'm pretty new to kirby, but I think that one would need to use `c::$data` and `c::get()` to make this work.

Let me know if you need any more infos on this.

**Comment by fvsch** [comment]
Good catch. This should be fixed in 3.0.1:
https://github.com/fvsch/kirby-twig/commit/c755d8b33bc4ee867a2230fa9596ce0114166625

Can you test on your side? (Both the classic and Composer install methods should work.)

**Comment by kraftner** [comment]
Wow, that was fast! :heart_eyes: Everything working as expected. Merci beaucoup!
