### ISSUE TITLE
Somehow allow adding safe functions

### ISSUE THREAD

**Issue by kraftner** [fvsch/kirby-twig#26]
Currently there is no way to add a helper function that `is_safe`. Maybe the internally used `* ` prefix can be used or you can consider exposing the Twig Environment. Haven't thought this through yet though.

**Comment by fvsch** [comment]
This should work in 3.0.1:
https://github.com/fvsch/kirby-twig/blob/master/doc/functions.md#marking-a-functions-output-as-safe

**Comment by kraftner** [comment]
Same here. Thanks a lot!
