### ISSUE TITLE
Twig 2 support coming soon?

### ISSUE THREAD

**Issue by bgarrant** [fvsch/kirby-twig#30]
Is Twig 2 support coming soon?

**Comment by fvsch** [comment]
Not sure, Twig 2.x can only be loaded with Composer, so that would mean dropping the classic install method *or* committing the full `vendor` directory from Composer.

Are there any features in Twig 2 that you use and which don’t exist in Twig 1.30+?

**Comment by fvsch** [comment]
Closing since I don't intend to update this plugin in the future.
