### ISSUE TITLE
Kirby 3 Version

### ISSUE THREAD

**Issue by seehat** [fvsch/kirby-twig#31]
Are you already working on an update for Kirby 3? - If not, I could help and start working on a pull request.

**Comment by fvsch** [comment]
Hi. I haven’t worked on it yet, and a PR would be great.

For Kirby 3, I was thinking about only supporting the Composer install method (which helps with Twig 2.x support, see #30). Would that work for you, or do you need a classic install method (zip download, extract in `site/plugins`) too?

**Comment by seehat** [comment]
Ok, then I will start.  

Me too. I think, the Composer install method will suit it better and fix #30.

**Comment by seehat** [comment]
#33

**Comment by seehat** [comment]
First version as pullrequest: #33

**Comment by fvsch** [comment]
Kirby 3 port in https://github.com/mgfagency/kirby-twig
