### ISSUE TITLE
Rename "main" branch to "master"

### ISSUE THREAD

**Issue by Sija** [fvsch/kirby-twig#40]
Please, don't break peoples' and software expectations...

**Comment by fvsch** [comment]
What software is currently broken by that branch name?

**Comment by Sija** [comment]
https://github.com/jprichardson/node-github-download is one example. I believe there might be many more since `master` is a standard name for main branch in git.

**Comment by fvsch** [comment]
`node-github-download` offers two ways to retrieve a specific branch. That should do the trick.

I'm happy with keeping the main branch named `main`.
