### ISSUE TITLE
Does this even work on Kirby 3?

### ISSUE THREAD

**Issue by eheiser** [fvsch/kirby-twig#41]
Been trying to get this to work on my Kirby3 test install to no avail... does this plugin even work or am I missing something?

**Comment by fvsch** [comment]
It doesn't. Someone else worked on porting to Kirby 3, it looks like it's usable but I haven't tried it.
https://github.com/mgfagency/kirby-twig

**Comment by eheiser** [comment]
Cheers mate, I got that version working. Thanks!
