### ISSUE TITLE
Example of how to use the new layout field using kirby-twig

### ISSUE THREAD

**Issue by sonicpunk** [fvsch/kirby-twig#42]
It would be nice to see an example of how to use the new layout field when using this plugin. Is it supported?

**Comment by fvsch** [comment]
Hi @sonicpunk. This plugin is not compatible with Kirby 3.x, and I believe you’re referring to a feature from Kirby 3.5?

See https://github.com/amteich/kirby-twig for Kirby 3.x support.

**Comment by sonicpunk** [comment]
Yes, I was ok. Thanks for the info!
